### ISSUE TITLE
WebUI - common and user's preferences

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#177]
WebUI module should be self sufficient for storing common preferences and user's preferences. This will avoid to install and operate a MongoDB database server for storing simple parameters.

Storing preferences in files should be sufficient.

**Comment by maethor** [comment]
Hm… How do you propose to do that ? Serialize and deserialize the configuration in pickle or json files ? Where can we store theses files ?

**Comment by mohierf** [comment]
Currently, JSON objects are store in Mongo or SQLite if one of these modules is installed.

If WebUI detects that there is not any installed module that allows to store users' preference, it will create some text files in a directory for storing JSON objects. In this directiry, on sub-directory for common preferences, and one sub-directory for each user ... this is quite simple and will allow to manage preferences without having to install a database server for such simple feature !

For instance, in */var/lib/shinken/webui* : 
```
global/
  widgets.json
  bookmarks.json
  ...

admin/
  widgets.json
  bookmarks.json
```

**Comment by maethor** [comment]
One question remains, what would be the point of the Mongo and SQL modules if the WebUI can store the things directly?

I don't see the point of having 20 backends. We should have one, one that works everywhere. It should be either flat JSON files or SQLite database. SQLite is risky because it may not be available on every distribution, while JSON files can be managed by python stdlib but would be quite inefficient.

The other thing to think about is how to import stuff from mongodb to theses JSON files.

**Comment by mohierf** [comment]
The WebUI will store preferences if no other module is installed and configured. If someone wants to store the user preferences in a database, we leave him install mongodb or Sqlite modules ...

We do not need to import anything into Json files ... because they are used only to store Web UI configuration ...
