### ISSUE TITLE
uri graph error with template

### ISSUE THREAD

**Issue by rom1701** [shinken-monitoring/mod-webui#351]
I have ui-graphite with the uri like  http://shinken.local/graphite
when i don't have graph template, i have graph in webui like  http://shinken.local/graphite/render/...
but if i have a template, the uri become: http://shinken.local/render/...

for information, i have ui-graphite refactored, and in log, the template is found by ui-graphite. and if i take the bad uri and modify with /graphite/, it work's

Have you a same problem?

**Comment by mohierf** [comment]
What you mean is that the graph URL is different when you have a template ... I do not use any template but as far as I know, the URL is depending of the used template and the templates are installed by the packs you installed on your server !

On my configuration, I found some files in * /var/lib/shinken/share/templates/graphite* directory, and the file `check_linux_cpu.graph` contains: 
```
${uri}render/?width=586&height=308&lineMode=connected&vtitle=CPU%20Usage%20(%)&target=alias(legendValue(${host}.${service}.cpu_prct_used%2C%22last%22)%2C%22CPU load%22)&fgcolor=000000&bgcolor=FFFFFF)&yMin=0
```

This problem is not a Web UI problem but a pack templates problem  ... you should open an issue in the corresponding pack.

**Comment by rom1701** [comment]
yes if i don't have a template, my uri is  http://shinken.local/graphite/render?with....
and if i have a template my uri is http://shinken.local/render?wit....

i think my template is good because if i take uri generated by my template and add /graphite/, it work.
and i did the test with default template give by ui-graphite, it's the same

OK thank, i open an issue ui-graphite

**Comment by mohierf** [comment]
I am  not very aware of ui-graphite ... perharps @Simage may help. You should alert with in your issue with @Simage in the text message ...

**Comment by Simage** [comment]
@rom1701 I'll try to take a look at it this weekend, I think I know where the problem is.

**Comment by mohierf** [comment]
Thanks @Simage !

**Comment by mohierf** [comment]
@rom1701 : have a look to the freshly updated `refactored` branch of ui-graphite ...  I just merged a PR made by @Simage
