### ISSUE TITLE
Better filtering from host services overview

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#378]
Links in the services overview of the host page should be filtered more precisely: 

Currently:
```
type:service hostname
```
Should be:
```
type:service ^hostname/
```

Using a regexp for the hostname will restrict to display only the services of the host `hostname` and not the services of hosts which name starts with `hostname` ...

**Comment by maethor** [comment]
For many reasons (mostly performance and security), I really don't like the idea of passing regexes in the search form. I prefer one of the two others solutions:
- Having an `exact_name` attribute in the `search_hosts_and_services()` method, and use this attribute in some views.
- Defining a syntax to pass an exact host or service name in the search field. For instance, the name could be surrounded by double quotes. So searching for `foo` would search all hosts and services having "foo" in their names, while search for `"foo"` would search all hosts and services which name is exactly "foo".

I prefer the second option, because it is a lot more generic, and allows the user to use it if needed.

**Comment by mohierf** [comment]
@maethor: any time to implement something on your side in the next days ?

**Comment by mohierf** [comment]
Last version implements a new filtering with double quotes ...
