### ISSUE TITLE
Nagvis in dashboard ?

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#421]
Hi,

Just a question:
I would like to know if there is an official method to display a nagvis graph in the Shinken's dashboard ?
If no, i will do a iframe in html (dashboard.tpl)
[link to nagvis](http://www.nagvis.org/screenshots)

Thx.

**Comment by zoza1982** [comment]
In new dev release of webui2 when you add a graph into dashboard, you can link it to any url instead of just element name. In my case , it was a link to aggregated  graph in graphite.

Here is how it looks like when you edit graph widget in dashboard:

<img width="374" alt="screen shot 2015-12-24 at 12 22 28 pm" src="https://cloud.githubusercontent.com/assets/11164593/11997733/1c6eb45a-aa39-11e5-83d5-f9f143c59ba9.png">

**Comment by Azef1** [comment]
Ok thx you. I will install dev release of webui2
