### ISSUE TITLE
Improvement Downtime:

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-webui#472]
Hi,
I propose some improvement about downtime in WebUI:
I see on this site all command to generate a downtime (Nagios): [here](https://old.nagios.org/developerinfo/externalcommands/commandlist.php?category_id=6&version_id=0&btnSubmit=Update)
Currently, WebUI doesn't implement some commands:

- Add feature to downtime a hostgroup **and** servicegroup:
![schedule_downtime_hostgroup](https://cloud.githubusercontent.com/assets/15362041/14245678/2d95d69e-fa63-11e5-94fd-aa26ffd14126.png)
When click on "Schedule a downtime":
![schedule_downtime_hostgroup_options](https://cloud.githubusercontent.com/assets/15362041/14245682/342ae300-fa63-11e5-9a93-490988bb1e5e.png)

Propose to schedule on one page:
Downtime for all hosts in hostgroup  AND/OR Downtime for all services of all host in hostgroup  

Same for servicegroup.

- When you schedule a downtime for a host add an option "Downtime children" to Schedules downtime for a specified host and all of its children (SCHEDULE_AND_PROPAGATE_TRIGGERED_HOST_DOWNTIME)

- Add feature to remove downtime for a hostgroup/Servicegroup
Create new function: 
DEL_ALL_HOSTGROUP_HOST_DOWNTIMES
DEL_ALL_HOSTGROUP_SVC_DOWNTIMES
DEL_ALL_SERVICEGROUP_HOST_DOWNTIMES
DEL_ALL_SERVICEGROUP_SVC_DOWNTIMES

In this file, [shinken-action.js](https://github.com/shinken-monitoring/mod-webui/blob/develop/module/htdocs/js/shinken-actions.js#L127) there are a remove function but not a "delete remove" to restore original parameters

**Comment by maethor** [comment]
Hello,

## first point

I really don't see any case where this would be useful. You must have a really strange use of the hostgroups and servicegroups.

With that said, another thing bothers me. If you downtime an host, all it's services will inherit this downtime. And I really don't see the point of putting a downtime on all the services, but not the hosts. So I don't think this check boxes are useful.

My point is, you can just click on the group title to get the list of services or hosts, then click « Select all elements », and then put a Downtime on all the elements selected.

## second point

I'm not sure what you means by "children", but when you put a downtime on a host or a service, all services and hosts depending on it are _de facto_ in downtime.

## third point

Same thing than the first point, I can't see any case where this would be useful. You never replied on https://github.com/shinken-monitoring/mod-mongo-logs/issues/7 but I really think you should'nt use hostgroups and servicegroups this way.

## last point

I think we should simply remove this "do_remove" function, because the webui should reflect the state of shinken and it's configuration. What do you think @mohierf ?

**Comment by Azef1** [comment]
Hi,
Thank for your answer.

### First point: 
I am agree with you "If you downtime an host, all it's services will inherit this downtime". But I am troubled by UI because when i click on "Schedule a downtime" 
![sidebar](https://cloud.githubusercontent.com/assets/15362041/14250284/fc543ed4-fa7d-11e5-86fa-f7237bdc89f9.PNG)
on sidebar the action is `SCHEDULE_HOST_DOWNTIME` So only on HOST. 
And when i select an host and i click on "Downtime" button 
![list](https://cloud.githubusercontent.com/assets/15362041/14250325/3315868a-fa7e-11e5-98f3-3d25e82f2c80.PNG)
, there are a popup, i can check the "Same downtime period for all services of the host" button. So this corresponds to the main purpose and the action is `SCHEDULE_HOST_DOWNTIME` AND  `SCHEDULE_SVC_DOWNTIME`
Why to have two differents downtime buttons ?

### Second point:
I do a test, i have add option `parents` in some "child' hosts. And when downtime the "parent" host, the downtime isn't propagate to the child host. I do the same test for service with dependency.


### Third point:
First, thank you very much about bp_rule, i has implemented the bp_rule in my conf and now it's more logic.
After discussion, i am agree isn't really useful to downtime a hostgroup or servicegroup because  "the select all" do the same thing. But when you downtime a host with those services, how you do to delete downtime (host+service inherit) ? Because when i click on
![all](https://cloud.githubusercontent.com/assets/15362041/14250834/7ef16202-fa80-11e5-8477-0998af02bf9d.PNG), the downtime on host is deleted but not for services. Have you same result ?


### Last point:
I propose to replace remove button by "delete downtime"

**Comment by maethor** [comment]
The downtime isn't propagated, but the effect. If you have an alert on a child element, this alert should not be notified because the parent element is in downtime… I think.

And yes, « Delete all downtimes » does not go into child elements (services or other form of child), this is completely normal. Again, you should not need to put downtime on everything, only on the parent (same thing for acknowledges).

**Comment by mohierf** [comment]
First of all, sorry for my being late on this subject ...

1/ scheduling a downtime on an host and its service is quite useful when all your monitoring is passive .... you need to schedule downtimes on services.

 2/ I will try to implement the same popup when the user click on dowtime in sidebar and bottom of an host. I do not remember why it is not this behavior currently.


 Should we agree with this ?

**Comment by Azef1** [comment]
I am agree :)

**Comment by mohierf** [comment]
It is not easily possible to use the same downtime process for both cases ... the downtime form that allows to enter a comment is only available when only one element is selected! If several elements are selected, this form can not be used and the WebUI schedules a default downtime (default time period and default comment ...).

I will commit a modification to propose the downtime scheduling form when only one element is selected in the list.

**Comment by mohierf** [comment]
Included in version 2.4
