### ISSUE TITLE
'Duration' reset in webui2 at each shinken config reload

### ISSUE THREAD

**Issue by aazudd** [shinken-monitoring/mod-webui#552]
Hi, 
I hope I am in the right place to ask.
I did install shinken 2.4 / webui2 (from pip). I was using shinken 1.4 / webui for about a year.

Since I start to test webui2, I can see at each configuration reload of shinken that I have to wait for all the checks to be (re-)done to have the results of the monitoring , and the 'duration' time is (of course) reset.
That was not the case with the old webui module with the older shinken version.

Is this the correct behavior ?
Did I miss something ?
How must the 'duration' time be considered ? What is his true sense ?

Thanks in advance for your help.

**Comment by mohierf** [comment]
Hi,
sorry but this not the right place for this ... your problem is due to a lack of retention with Shinken. I suppose you did not installed a retention module and you previsouly had one. Thus, on each Shinken restart, your hosts/services are in their initial state and Shinken must recheck all from scratch ...

**Comment by aazudd** [comment]
Thank you for pointing me out the problem !
You are right, I forgot to install a retention module.

Sorry for the noise.
And thank you again for your work with webui2.
