### ISSUE TITLE
Use status bar states to refine the search

### ISSUE THREAD

**Issue by guillaume-u** [shinken-monitoring/mod-webui#581]
Hello,

When I make a search like "Test", I get this view (that is normal) :

![shinken_01](https://user-images.githubusercontent.com/469104/30168463-c03a5a12-93e9-11e7-8e3c-b6b538653e07.png)

But, if I click on the status bar : 8/X (where my cursor is), "Test" is not in the search query anymore and returns all services, as below : 
![shinken_02](https://user-images.githubusercontent.com/469104/30168615-3e03300e-93ea-11e7-9372-116dc93115d8.png)

Thanks for your help :)

**Comment by maethor** [comment]
Hello @guillaume-u 

Thanks for this issue, and thank you for using this WebUI :)

This is "normal" because the status bar links are pre-programmed searches.

In your example you see "8/16555 OK services". Clicking on this link doesn't narrow the search to give you only the 8 "Test is:ok" services, but replaces the search to give you all of the 16555 "is:ok" services.

This is the expected behavior because the other option would be pretty hard to develop. Because if you allow to enable disabled filters, you have to allow to disable enabled filters… it became quite hard to manage.

Moreover, what if the search is "Test is:WARNING" and you click on the "OK" link? Do you want "Test is:WARNING is:OK", which doesn't get you anything? Do you want "Test is:OK"? So now I need to replace certain parts of the search string, and keep others.

I agree it could be better, but the current behavior is actually a good balance between usability and code complexity. So the best can do is to learn some filters and search for "Test is:ok". 

What do you think @guillaume-u? I am open to talk about on this.

**Comment by guillaume-u** [comment]
Hello @maethor 

Thanks for your reply.

> In your example you see "8/16555 OK services". Clicking on this link doesn't narrow the search to give you only the 8 "Test is:ok" services, but replaces the search to give you all of the 16555 "is:ok" services.

Yes, exactly.

> This is the expected behavior because the other option would be pretty hard to develop. Because if you allow to enable disabled filters, you have to allow to disable enabled filters… it became quite hard to manage.

I think, but maybe I'm wrong, clicking on this "div" should only a filter once like "is:Warning", "is:OK", ..., to the current query. _(see  below why I'm thinking that)_.

> Moreover, what if the search is "Test is:WARNING" and you click on the "OK" link? Do you want "Test is:WARNING is:OK", which doesn't get you anything? Do you want "Test is:OK"? So now I need to replace certain parts of the search string, and keep others.

In my mind, If I search "Test is:WARNING" the "OK", "Error", ... links should be at at 0/X (as I ask for Warning state only).
So it will not be possible to make the query "Test is:WARNING is:OK" via the WebUI.

Thanks again.

Guillaume.

**Comment by maethor** [comment]
Sorry, I'm a little bit late on this. Indeed your proposition is interesting. I don't know if I will find time to work in this, but it seems easy to do.

**Comment by maethor** [comment]
@guillaume-u I implemented what said. So when the button is not greyed, it appends 'is:…' in the search. And when the button is greyed it erases the current search.

The code has been pushed on integ branch, I plan to publish a new version of the webui in a few days.
