### ISSUE TITLE
[WebUI 2.6.1] Issue on Acknolegdement

### ISSUE THREAD

**Issue by xsylx** [shinken-monitoring/mod-webui#589]
Since i have update WebUI to 2.6.1, acknoledgement isn't possible with button located on business impact banner.

![2017-10-06_16h22_48](https://user-images.githubusercontent.com/16323410/31282430-d4e64518-aab2-11e7-9ef6-f831994fd551.png)

Button located on left side works.

Any idea ?

**Comment by maethor** [comment]
Thank you for your report @SylvainGuibert 

I believe you also have the bug in the problems view. I am currently working on a complete rewrite of theses actions for 2.7. Since this is not critical (you can use other buttons to ACK), this bug will be fixed soon but not in the 2.6 branch.

I'll keep you posted when 2.7 is released.

**Comment by maethor** [comment]
@SylvainGuibert I just released 2.7.0. Can you try and let me know if your bug is fixed?

**Comment by xsylx** [comment]
@maethor : it seems to be ok with 2.7.1 . Thx for your job !

**Comment by maethor** [comment]
Great! ;)
