### ISSUE TITLE
Error 500 in System/Alerts

### ISSUE THREAD

**Issue by KroMignon** [shinken-monitoring/mod-webui#606]
#Version
Shinken: 2.4.3
WebUI: 2.7.1
OS: Debian GNU/Linux 7.11 (wheezy)

# Problem
Got error 500 when selecting System/Alerts
```
Error: 500 Internal Server Error

Sorry, the requested URL 'http://xxxxxxxxxxx:7767/stats' caused an error:

Internal Server Error
Exception:

ZeroDivisionError('float division by zero',)
Traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui2/module.py", line 509, in lock_version
    return f(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3619, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3595, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3399, in render
    self.execute(stdout, env)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3386, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui2/plugins/stats/views/stats.tpl", line 13, in <module>
    <tr><td>{{ other }} ({{ round((other / float(total)) * 100, 1) }}%)</td><td><strong>Others</strong></td></tr>
ZeroDivisionError: float division by zero

```

**Comment by pydubreucq** [comment]
Hi,
Same error for us 
http://forum.shinken-monitoring.org/threads/10630-Impossible-d-acc%E9der-aux-stats-et-logs
Bye

**Comment by maethor** [comment]
Hi,

Thank you for reporting this issue here. Indeed, I am not present on the forum.

In fact, I just realized this module cannot work for anyone except me, because I have hardcoded a filter that will not work for you. I will try to fix it this week.

**Comment by KroMignon** [comment]
Hi maethor,

is it not here the right place to submit issues?
Is there a bug tracker somewhere else for WebUI?

**Comment by maethor** [comment]
@KroMignon It is the right place, yes. Github is the official bug tracker for the WebUI.

I don't have too much time because December is always a busy month in my company, but I will try to look at this as soon as possible.

**Comment by joshsutton** [comment]
@maethor Have you had any time to take a look at this issue? 

Thanks so much for your time!

**Comment by maethor** [comment]
@joshsutton nope, and with Meltdown and Spectre, I will be busy for a few days :-(

I promise I will not forget you.

In fact, this problem is quite hard. I cannot make stats on every logged notifications, right? Because if you have an alert that is notified three time by email to 20 people, and an alert that is notified 60 times on your chatroom, your stats should show the second, and not the first.

The solution I found is to filter the notifications on the `notification_command`, and to compute stats only on my `notify_by_chat` notifications. But obviously this is only working on my setup, because I get all the notifications on my chatroom before they escalade elsewhere (or not, and anyway they continue to be sent to my chatroom). And for the moment I don't see how to make it work otherwise. I don't see how to make a generic and smart filter that will work for every setup.

Do you have any idea?

**Comment by anthony-sticky** [comment]
Hi,
Do you have any update on this issue @maethor please?

**Comment by anthony-sticky** [comment]
@joshsutton @KroMignon @pydubreucq Did you find any way to fix this?

**Comment by maethor** [comment]
No update because as I said earlier I don't know how to fix this. As I am the only one looking for it, one day I will find a solution, maybe, I don't know.

**Comment by anthony-sticky** [comment]
Arf OK, I can't help here unfortunately

**Comment by mohierf** [comment]
@maethor: this is to be discussed. I have an idea for this ...

**Comment by maethor** [comment]
You have all my attention :)

**Comment by mmpx12** [comment]
2019 and still not fix ...

**Comment by maethor** [comment]
2019 but still only 2 devs on this project. You are very welcome to propose a fix @mmpx12 

Until then, know that this kind of comment is not appreciated.

**Comment by pykiki** [comment]
Je proposerai bien ceci, en gros `% if total != 0:` :

```
--- a/module/plugins/stats/views/stats.tpl
+++ b/module/plugins/stats/views/stats.tpl
@@ -7,10 +7,14 @@
     <div class="panel-heading"><h3 class="panel-title">{{ total }} host alerts</h3></div>
     <table class="table table-striped table-condensed">
       %for l in hosts.most_common(15):
+      % if total != 0:
       <tr><td width="160px">{{ l[1] }} ({{ round((l[1] / float(total)) * 100, 1) }}%)</td><td><a href="/stats/host/{{ l[0] }}?days={{ days }}">{{ l[0] }}</a></td></tr>
+      % end
       %end
       %other = sum((h[1] for h in hosts.most_common()[15:]))
+      % if total != 0:
       <tr><td>{{ other }} ({{ round((other / float(total)) * 100, 1) }}%)</td><td><strong>Others</strong></td></tr>
+      % end
     </table>
   </div>
 </div>
@@ -20,10 +24,14 @@
     <div class="panel-heading"><h3 class="panel-title">{{ total }} services alerts</h3></div>
     <table class="table table-striped table-condensed">
       %for l in services.most_common(15):
+      % if total != 0:
       <tr><td width="160px">{{ l[1] }} ({{ round((l[1] / float(total)) * 100, 1) }}%)</td><td><a href="/stats/service/{{ l[0] }}?days={{ days }}">{{ l[0] }}</a></td></tr>
+      % end
       %end
       %other = sum((s[1] for s in services.most_common()[15:]))
+      % if total != 0:
       <tr><td>{{ other }} ({{ round((other / float(total)) * 100, 1) }}%)</td><td><strong>Others</strong></td></tr>
+      % end
     </table>
   </div>
 </div>
@@ -33,10 +41,14 @@
     <div class="panel-heading"><h3 class="panel-title">{{ total }} hosts/services alerts</h3></div>
     <table class="table table-striped table-condensed">
       %for l in hostsservices.most_common(15):
+      % if total != 0:
       <tr><td width="160px">{{ l[1] }} ({{ round((l[1] / float(total)) * 100, 1) }}%)</td><td>{{ l[0] }}</td></tr>
+      % end
       %end
       %other = sum((h[1] for h in hostsservices.most_common()[15:]))
+      % if total != 0:
       <tr><td>{{ other }} ({{ round((other / float(total)) * 100, 1) }}%)</td><td><strong>Others</strong></td></tr>
+      % end
     </table>
   </div>
 </div>
```

**Comment by maethor** [comment]
Hi everyone,

I hope you will be very happy, I finally found a way to publish this feature and make it work for everyone.

So, the idea is that the notifications needs to be filtered before computing stats, because we don't want to count a notification 4 times if it is sent to 4 people.

By default, no filter is configured, so it works but probably the stats are not so great. So the webui will invite you to filter either by `command_name` (`notify-service-by-slack` for instance) or by `contact_name`.

And if not log is found, no more 500, you will get a nice message to help you configure the webui.

I plan to publish this in a new webui version in some days.
