### ISSUE TITLE
Problems view, some ideas

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#638]
My current problems view: 
![image](https://user-images.githubusercontent.com/2932687/48841576-18b01080-ed92-11e8-8c65-32c41223c819.png)

Few minutes later: 
![image](https://user-images.githubusercontent.com/2932687/48841616-3da48380-ed92-11e8-9ac5-0d5f494c34df.png)

On the first picture, the hosts/services synthesis shows no host and no services whereas I have 41 hosts and 200 services in my test configuration. Indeed there is no problem with this information ... because I do not have any host nor service matching the current filter ! It is a bit disappointing because the hosts/services synthesis do not say **0 hosts out of 41** and **0 services out of 200**

- [x] adding the hosts/services count in the synthesis

The first image shows a message "What a bummer! We coulc not find anything".  All the better nothing was found ... there is not yet any problem raised. I would have appreciated a message like "All the better! No problems are unhandled on your system"

- [x] on the default filter in the problems view, change the message

On the first image, the host synthesis popover indicates 1 host problem whereas there is no badge on the hsot icon. This is because there is an host DOWN in SOFT state and the icon only has a badge for HARD states. We should not count a problem for a SOFT state but only for HARD ones ...

- [x] do not count a problem for a SOFT state

On the second image, the service UNREACHABLE state dot not have a specific icon. This state is allowed for a service when one is using the Alignak framework

- [x] define an icon for the UNREACHABLE service state

When clicking on an host name in the problems list, one expect to navigate to the host page, but nope ... it opens the host list content like when one click on any other part of the host/service row

- [x] click on the host name link navigates to */host/host_name*

**Comment by mohierf** [comment]
@maethor I am interested in your feedback about these ideas 😉

**Comment by mohierf** [comment]
One more ...
![image](https://user-images.githubusercontent.com/2932687/48843856-9e36bf00-ed98-11e8-80b9-4e7fa6340999.png)

As of now, 15 services problems but no badge on the services icon whereas some of them are in a HARD state

- [ ] services icon badge for HARD problems

**Comment by maethor** [comment]
OK, It could be quite hard to discuss on many points, Github is not been made for this, but I will try.

* adding the hosts/services count in the synthesis : OK
* on the default filter in the problems view, change the message : This is a generic search, you are not always looking for problems. What if you search only a server name, without any state filter, and it does not find it? So I prefer keeping this generic message unless you find an elegant way to display a different message only when this is a search for problems.
* do not count a problem for a SOFT state : OK
* define an icon for the UNREACHABLE service state : OK.
* click on the host name link navigates to /host/host_name : Yeah. I choose to do this, because I was thinking we should have all the main informations in /problems view. But I think it was a mistake. We should revert and make host name link open the /host page.
* services icon badge for HARD problems : OK. (On my setup I have never seen any badge neither on service nor host icons, I don't know why).

Thanks.

**Comment by mohierf** [comment]
👍 thanks for your answers. I will manage all this stuff in a next PR.

**Comment by mohierf** [comment]
Closed thanks to #654
