### ISSUE TITLE
About "integ" branch with ui-graphite submodule

### ISSUE THREAD

**Issue by rednach** [shinken-monitoring/mod-webui#715]
We are trying to move from shinken to alignak, mainly because of backend architecture. But curent users are used to use shinken UI and their graphs (In some aspects I prefer it to alignak one, too). So, I am working in a environment with:
 - alignak-broker with modules shinken_webui and (disabled) ui_graphite2
 - shinken_webui ("integ" branch) with module ui_graphite2 and somre hacks (importing alignak ModulesManager and Daemon when ALIGNAK mode, enabling ui_graphite2 in runtime, ...)
 - mod-ui-graphite hacked in a similar way that integ branch (installed as python module, ALIGNAK_SHINKEN_UI env, BaseModule from alignak, etc.)

Probably, too many tricks.
So, my question is about evolution of integ branch in mod-webui, how to integrate graphs into alignak with shinken-webui, etc. Do you prefer to take a look to my (messy) approach?
Thank you very much for your effort.

**Comment by mohierf** [comment]
Hi @rednach 
I created the integ branch as an approach to use the Shinken WebUI with my Amlignak framework and it really looks promising. since several months up to now I am using this in a production environment and it is really stable.
It's been a while since I did some modifications to finish the job andI am really interested in you approach. Would you mind submittingg a PR in the project and I will comment ?

**Comment by mohierf** [comment]
As of now, I am trying to build an Alignak Docker image that includes the Web Ui ... this may help :wink:

**Comment by rednach** [comment]
https://github.com/shinken-monitoring/mod-webui/pull/716

**Comment by maethor** [comment]
Hi.
Can we close this issue?
